version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - .env
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./hleb:/hleb
      - ./log:/log
    ports:
      - '${SERVER_EXTERNAL_PORT}:80'

  php:
    environment:
      PHP_IDE_CONFIG: 'serverName=toaster'
    build: ./docker
    env_file:
      - .env
    volumes:
      - ./hleb:/hleb
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'ok'
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '${DATABASE_EXTERNAL_PORT}:3306'

  pma:
    image: phpmyadmin
    environment:
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${PMA_EXTERNAL_PORT}:80'
